#!/usr/bin/perl
# Compiles the DLSS-NR colour codec to SPIR-V, for the Vulkan backend.
#
# The shader is NOT copied. It is extracted verbatim from codec::kShaderSource in
# dlssnr/DlssNr_Codec.h -- the same string the D3D11 and D3D12 paths compile at runtime -- so there is
# exactly one source and no way for the Vulkan variant to quietly drift from the other two.
#
# No source modification is needed either. The shader declares plain `register(t0)` style bindings, and
# dxc's -fvk-*-shift flags map each register class onto its own run of Vulkan descriptor bindings:
#
#     b0        -> binding 0      constants
#     t0 .. t4  -> binding 1 .. 5 source, model, original, motion, ratio history
#     u0 .. u1  -> binding 6 .. 7 target, keep
#     s0        -> binding 8      the linear sampler
#
# DlssNr_Codec_Vk.h's descriptor set layout must match that table.
#
# Run from this directory:  perl build_vk_shader.pl
# Requires dxc from the Vulkan SDK (the Windows SDK's dxc does not emit SPIR-V).

use strict;
use warnings;
use File::Basename;

my $dir     = dirname(__FILE__);
my $header  = "$dir/../../dlssnr/DlssNr_Codec.h";
my $hlsl    = "$dir/DlssNr_Codec.gen.hlsl";
my $spv     = "$dir/DlssNr_Codec.gen.spv";
my $out     = "$dir/../../dlssnr/DlssNr_Codec_Vk_Bytecode.h";

# ---------------------------------------------------------------------------------------------------
# Find dxc. The Vulkan SDK's build is the one that can emit SPIR-V.

my $dxc;
for my $candidate (glob('C:/VulkanSDK/*/Bin/dxc.exe'), $ENV{DXC})
{
    next unless defined $candidate && -x $candidate;
    $dxc = $candidate;
}

die "dxc.exe not found. Install the Vulkan SDK, or set DXC to its path.\n" unless defined $dxc;

# ---------------------------------------------------------------------------------------------------
# Extract the shader.

open(my $fh, '<', $header) or die "cannot read $header: $!\n";
my $source = do { local $/; <$fh> };
close($fh);

my ($body) = $source =~ /kShaderSource\s*=\s*R"\((.*?)\)"\s*;/s;
die "could not find codec::kShaderSource in $header\n" unless defined $body;

# The literal is written as several adjacent raw strings so it stays readable; stitch them back.
$body =~ s/\)"\s*R"\(//gs;

open(my $out_hlsl, '>', $hlsl) or die "cannot write $hlsl: $!\n";
print $out_hlsl "// GENERATED by build_vk_shader.pl from dlssnr/DlssNr_Codec.h -- do not edit.\n";
print $out_hlsl $body;
close($out_hlsl);

# ---------------------------------------------------------------------------------------------------
# Compile.

my @cmd = ($dxc, '-T', 'cs_6_0', '-E', 'main', '-spirv',
           '-fvk-b-shift', '0', '0',
           '-fvk-t-shift', '1', '0',
           '-fvk-u-shift', '6', '0',
           '-fvk-s-shift', '8', '0',
           '-Fo', $spv, $hlsl);

print "compiling: @cmd\n";
system(@cmd) == 0 or die "dxc failed\n";

# ---------------------------------------------------------------------------------------------------
# Emit the bytecode header.

open(my $bin, '<:raw', $spv) or die "cannot read $spv: $!\n";
my $blob = do { local $/; <$bin> };
close($bin);

die "SPIR-V is empty\n" unless length($blob);
die "SPIR-V length is not a multiple of 4\n" if length($blob) % 4;

my @words = unpack('V*', $blob);

open(my $hdr, '>', $out) or die "cannot write $out: $!\n";
print $hdr <<"EOT";
#pragma once

// GENERATED by shaders/dlssnr/build_vk_shader.pl -- do not edit.
//
// The DLSS-NR colour codec, compiled to SPIR-V from codec::kShaderSource in DlssNr_Codec.h. That
// string is the single source for all three backends; D3D11 and D3D12 compile it at runtime, and
// Vulkan cannot, so it is compiled here instead.
//
// Descriptor bindings, set by dxc's register shifts (see the script):
//   0        constants
//   1 .. 4   source, model, original, motion
//   5 .. 6   target, keep
//   7        linear sampler
//
// Regenerate after any change to the shader.

#include <cstdint>

namespace codec
{
inline constexpr uint32_t kCodecSpirv[] = {
EOT

for (my $i = 0; $i < @words; $i += 8)
{
    my $end = $i + 7 < $#words ? $i + 7 : $#words;
    print $hdr "    " . join(', ', map { sprintf('0x%08x', $_) } @words[$i .. $end]) . ",\n";
}

print $hdr "};\n} // namespace codec\n";
close($hdr);

printf("wrote %s (%d words, %d bytes)\n", $out, scalar(@words), length($blob));
