// GENERATED by build_vk_shader.pl from dlssnr/DlssNr_Codec.h -- do not edit.

cbuffer Params : register(b0)
{
    uint  gMode;
    float gWhitePoint;
    uint  gWidth;
    uint  gHeight;
    float gTransferStrength;
    float gColourStrength;
    uint  gDebugView;
    float gMaxRatio;
    uint  gPassthrough;
    float gMvScaleX;     // motion vector units -> pixels of this dispatch
    float gMvScaleY;
    uint  gGuideWidth;   // the motion texture's valid region
    uint  gGuideHeight;
    // How strongly to distrust the model's colour where it desaturated what it was shown. 0 disables.
    float gColourGuard;
};

// How much colour a pixel has, independent of how bright it is: 0 is neutral, 1 fully saturated.
//
// Used to ask whether the model kept the chroma it was given. A ratio of two of these is meaningful
// where a difference of two colours is not, because the proxy and the model sit at different
// brightnesses by construction.
float Saturation(float3 c)
{
    const float hi = max(c.r, max(c.g, c.b));
    const float lo = min(c.r, min(c.g, c.b));
    return hi > 1e-6 ? (hi - lo) / hi : 0.0;
}

// Values the arithmetic below cannot reason about, bounded.
//
// A game's scene colour is an open-ended linear buffer, and a sun can arrive in it as infinity --
// R11G11B10_FLOAT, which is what Borderlands 4 hands its upscaler, represents Inf perfectly well. The
// normalisation below then computes rolled / displayLuma as 1 / Inf, which is zero, and multiplies
// that back into an infinite channel. Inf * 0 is NaN. The model is handed the NaN and what comes back
// is a block of garbage where the sun was.
//
// It matters more in the reordered arrangements than in post-process: those work on the game's own
// scene colour, where the sun is still at full intensity, rather than on an upscaler's output.
//
// A comparison rather than isfinite(): a NaN fails every comparison, so this replaces it with zero in
// the same expression that bounds an infinity, and behaves identically on cs_5_0 and cs_6_0.
static const float kSceneCeiling = 65504.0; // the largest finite half, which is what these buffers hold

float SanitizeChannel(float v) { return (v > 0.0) ? min(v, kSceneCeiling) : 0.0; }

float3 Sanitize(float3 c)
{
    return float3(SanitizeChannel(c.r), SanitizeChannel(c.g), SanitizeChannel(c.b));
}

// Colours outside the AP1 gamut are impossible on any display and read as sparkle where a bright
// saturated pixel is pushed further. Clamping inside AP1 and coming back keeps everything reachable.
float3 ClampAp1(float3 color)
{
    const float3x3 bt709_to_ap1 = { 0.613097, 0.339523, 0.047379,
                                    0.070194, 0.916354, 0.013452,
                                    0.020616, 0.109570, 0.869815 };
    const float3x3 ap1_to_bt709 = { 1.705051, -0.621792, -0.083259,
                                    -0.130256, 1.140805, -0.010548,
                                    -0.024003, -0.128969, 1.152972 };
    return mul(ap1_to_bt709, max(mul(bt709_to_ap1, color), float3(0.0, 0.0, 0.0)));
}

// ---------------------------------------------------------------------------------------------
// The composition below (UpgradeToneMap's two-branch ratio, the OkLab hue correction, and the blend
// between a luminance-only result and the model's own colour) is taken from RenoDX's DLSS 5 addon by
// clshortfuse -- https://github.com/clshortfuse/renodx. It is their design, not ours; see
// Licenses/RenoDX_LICENSE.txt. The OkLab matrices are Bjorn Ottosson's published constants and the
// AP1, sRGB and PQ transforms are standard colour science.
// ---------------------------------------------------------------------------------------------

// OkLab, so the model's colour can be reached without its hue being invented on the way. A ratio
// applied to an RGB triple does not move hue, but a difference added to one does -- which is what the
// old composition did, and why a warm subject could come back green. Here the result's chroma is
// rebuilt in the model's own hue direction and only its magnitude is taken from the scaled colour.
float3 CbrtSigned(float3 v) { return sign(v) * pow(abs(v), 1.0 / 3.0); }

float3 ToOkLab(float3 color)
{
    const float3x3 rgb_to_lms = { 0.4122214708, 0.5363325363, 0.0514459929,
                                  0.2119034982, 0.6806995451, 0.1073969566,
                                  0.0883024619, 0.2817188376, 0.6299787005 };
    const float3x3 lms_to_lab = { 0.2104542553, 0.7936177850, -0.0040720468,
                                  1.9779984951, -2.4285922050, 0.4505937099,
                                  0.0259040371, 0.7827717662, -0.8086757660 };
    return mul(lms_to_lab, CbrtSigned(mul(rgb_to_lms, color)));
}

float3 FromOkLab(float3 lab)
{
    const float3x3 lab_to_lms = { 1.0, 0.3963377774, 0.2158037573,
                                  1.0, -0.1055613458, -0.0638541728,
                                  1.0, -0.0894841775, -1.2914855480 };
    const float3x3 lms_to_rgb = { 4.0767416621, -3.3077115913, 0.2309699292,
                                  -1.2684380046, 2.6097574011, -0.3413193965,
                                  -0.0041960863, -0.7034186147, 1.7076147010 };
    float3 lms = mul(lab_to_lms, lab);
    return mul(lms_to_rgb, lms * lms * lms);
}

// Takes the hue and the chroma direction from `correct`, and only the chroma magnitude from
// `incorrect`. Scaling a colour by a luminance ratio changes how saturated it reads; this puts the
// saturation back where the model meant it without letting the hue drift.
float3 HueOkLab(float3 incorrect, float3 correct)
{
    float3 incorrectLab = ToOkLab(incorrect);
    const float3 correctLab = ToOkLab(correct);
    const float incorrectChroma = length(incorrectLab.yz);
    const float correctChroma = length(correctLab.yz);
    incorrectLab.yz = correctLab.yz * (correctChroma == 0.0 ? 1.0 : incorrectChroma / correctChroma);
    return ClampAp1(FromOkLab(incorrectLab));
}

Texture2D<float4>   gSource   : register(t0);  // encode: the frame. resolve: the proxy.
Texture2D<float4>   gModel    : register(t1);  // resolve: what the model returned.
Texture2D<float4>   gOriginal : register(t2);  // resolve: the untouched frame.
Texture2D<float4>   gMotion   : register(t3);  // resolve, accumulating: the game's motion vectors.
RWTexture2D<float4> gTarget   : register(u0);  // encode: the proxy. resolve: the frame.
RWTexture2D<float4> gKeep     : register(u1);  // encode: the untouched copy. resolve: the edit history.
SamplerState        gLinear   : register(s0);  // so the edit can be read at a different size

static const float3 kLuma = float3(0.2126, 0.7152, 0.0722);

// sRGB rather than a plain 2.2 power: it is what an SDR game buffer actually carries, and the model was
// trained on those.
float3 LinearToSrgb(float3 v)
{
    v = saturate(v);
    return lerp(v * 12.92, 1.055 * pow(max(v, 1e-8), 1.0 / 2.4) - 0.055, step(0.0031308, v));
}

float3 SrgbToLinear(float3 v)
{
    v = saturate(v);
    return lerp(v / 12.92, pow((v + 0.055) / 1.055, 2.4), step(0.04045, v));
}

// The edit at an arbitrary position, exactly as the resolve computes its own.
float3 EditAt(float2 uvq)
{
    float3 p = gSource.SampleLevel(gLinear, uvq, 0).rgb;
    float3 m = gModel.SampleLevel(gLinear, uvq, 0).rgb;

    if (gPassthrough == 0)
    {
        p = SrgbToLinear(p);
        m = SrgbToLinear(m);
    }

    return m - p;
}


[numthreads(8, 8, 1)]
void main(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= gWidth || id.y >= gHeight)
        return;

    // Normalised, so the source may be any size relative to this dispatch.
    float2 uv = (float2(id.xy) + 0.5) / float2(gWidth, gHeight);

    /*
     * Mode 3 -- carry the model's edit from the resolved image onto the jittered one.
     *
     * This is what lets the multi-pass chain end in a real Super Resolution pass. The first pass
     * resolves the game's jitter so the model can work on a clean, antialiased frame, but that same
     * resolve is what leaves the enlargement with no subpixel variation to reconstruct from. Handing
     * the enlargement the resolved frame therefore costs it everything DLSS is good at.
     *
     * So the edit is measured here rather than delivered here: how much brighter or darker the model
     * made each pixel, as a ratio against what it was shown. That ratio is then applied to the game's
     * ORIGINAL jittered frame, which still carries its full subpixel content. The enlargement gets a
     * properly jittered image with the model's enhancement riding on it, and the game's real jitter
     * offsets to go with it.
     *
     * A luminance ratio, not a per-channel one. The edit is a brightness decision -- that is what the
     * composition established -- and applying it per channel would drag the jittered frame's hue
     * toward the resolved frame's, which is not a transfer of anything, just a second colour pass.
     *
     * gSource   what the model was shown  (the first pass's resolved output)
     * gModel    what it returned          (the same image, enhanced)
     * gOriginal the game's jittered frame (what the enlargement should actually see)
     */
    if (gMode == 3)
    {
        const float3 before = Sanitize(gSource.Load(int3(id.xy, 0)).rgb);
        const float3 after = Sanitize(gModel.Load(int3(id.xy, 0)).rgb);
        const float4 jittered = gOriginal.Load(int3(id.xy, 0));

        const float beforeLuma = dot(before, kLuma);
        const float afterLuma = dot(after, kLuma);

        /*
         * Below the noise floor the ratio is meaningless -- a pixel the first pass resolved to almost
         * nothing divides into anything at all -- so those are passed through rather than amplified.
         */
        float ratio = 1.0;

        if (beforeLuma > 1e-4)
            ratio = clamp(afterLuma / beforeLuma, 1.0 / max(gMaxRatio, 1.0), gMaxRatio);

        gTarget[id.xy] = float4(Sanitize(jittered.rgb) * ratio, jittered.a);
        return;
    }

    if (gMode == 2)
    {
        gTarget[id.xy] = gSource.SampleLevel(gLinear, uv, 0);
        return;
    }

    if (gMode == 0)
    {
        float4 source = gSource.Load(int3(id.xy, 0));
        float3 frame = Sanitize(source.rgb);

        // Kept so the resolve has the frame as it was, rather than having to reconstruct it.
        gKeep[id.xy] = float4(frame, source.a);

        // Some games hand DLSS a frame that has already been through their tonemapper. The game says
        // which in its own DLSS creation flags, and converting one that needs no conversion is pure
        // damage, so it goes through untouched.
        if (gPassthrough != 0)
        {
            gTarget[id.xy] = float4(frame, source.a);
            return;
        }

        // What the model is shown. Mode 2 -- the default -- scales the frame and encodes it, and that
        // is all: the game is going to tone map this picture later, so tone mapping it here as well
        // shows the model a doubly compressed image. Measured against Cyberpunk's own numbers, the
        // Reinhard proxy handed the model a scene value of 1.0 as 0.55 and 1.5 as 0.64 -- flat, dark,
        // and nothing like the finished frame it was trained on. The model then synthesised weakly,
        // judged tone on a picture that does not exist, and its answer had to be un-crushed on the way
        // back. Mode 0 keeps that old curve, mode 1 the fitted one.
        float luma = dot(frame, kLuma);
        float3 display = frame / max(gWhitePoint, 1e-4);

        // A soft knee instead of a hard ceiling. Anything the curve leaves above 0.75 is rolled off
        // rather than clipped, so the model is never shown a field of flat white whose blown pixels
        // flip between frames -- unstable input is unstable output, and this is where a bright scene
        // would produce it.
        float displayLuma = dot(display, kLuma);

        if (displayLuma > 0.75)
        {
            float rolled = 0.75 + 0.25 * (1.0 - exp(-(displayLuma - 0.75) / 0.25));
            display *= rolled / displayLuma;
        }

        gTarget[id.xy] = float4(LinearToSrgb(display), source.a);
        return;
    }

    // Sampled rather than loaded: when the model ran at a reduced resolution these are smaller than the
    // frame, and its edit is enlarged here while the frame underneath stays untouched.
    float4 proxySample = gSource.SampleLevel(gLinear, uv, 0);
    float4 modelSample = gModel.SampleLevel(gLinear, uv, 0);

    // Nothing was encoded on the way in, so nothing is decoded here either.
    float3 proxy = Sanitize(gPassthrough != 0 ? proxySample.rgb : SrgbToLinear(proxySample.rgb));
    float3 model = Sanitize(gPassthrough != 0 ? modelSample.rgb : SrgbToLinear(modelSample.rgb));
    float4 originalSample = gOriginal.Load(int3(id.xy, 0));

    // All three pictures have to share a scale before their luminances can be compared. The proxy and
    // the model come back from an sRGB decode, so they sit in 0..1 where 1 is the white point; the
    // frame is raw linear and runs well past that. Comparing them unnormalised is a real bug and it
    // reads exactly like the model has stopped adding detail: with the frame several times larger,
    // the shadow branch never fires, every pixel takes the highlight branch, and the clamp flattens
    // the result to a near-constant scale. Colour still moves, because that comes from the model's
    // own hue, which is what makes the failure so confusing to look at.
    const float normScale = gPassthrough != 0 ? 1.0 : max(gWhitePoint, 1e-4);
    float3 original = Sanitize(originalSample.rgb) / normScale;

    float originalLuma = dot(original, kLuma);
    float proxyLuma = dot(proxy, kLuma);

    if (gDebugView == 1)
    {
        gTarget[id.xy] = float4(proxy * gWhitePoint, originalSample.a);
        return;
    }

    if (gDebugView == 2)
    {
        gTarget[id.xy] = float4(model * gWhitePoint, originalSample.a);
        return;
    }

    float3 edit = model - proxy;

    // Coring was tried here and removed: the per-frame churn's amplitude overlaps the real detail's,
    // so an amplitude threshold cannot separate them -- it only relocated the noise to the threshold.

    if (gDebugView == 3)
    {
        // Amplified and centred on grey, so both directions of the edit are visible at once.
        float3 shown = saturate(0.5 + edit * 20.0);
        gTarget[id.xy] = float4(SrgbToLinear(shown) * gWhitePoint, originalSample.a);
        return;
    }

    // The edit, averaged over time. The model re-decides a measurable fraction of its answer every
    // frame even on a static scene; blending each frame's edit with its own reprojected history keeps
    // the consistent part -- the detail -- and cancels the part that re-randomises. NVIDIA's own
    // motion vectors carry the history to where the surface is now.

    // The composition. The model's answer is not treated as a difference to add onto the frame -- it
    // is a complete picture in its own right, and it is brought back by rescaling it to sit where the
    // original's luminance says it should. Adding a difference is what let colour run away: nothing
    // bounded where the sum landed, so a warm subject could arrive green. Here both ends of every
    // blend are well-formed pictures, so everything between them is one too.
    float modelLuma = dot(model, kLuma);
    float3 upgraded;

    if (modelLuma <= 1e-5)
    {
        // The model can return an empty frame for an input it cannot read. Rescaling that collapses
        // the picture to black, so the frame is handed back untouched instead.
        upgraded = original;
    }
    else
    {
        float ratio;

        if (originalLuma < proxyLuma)
        {
            // Below what the proxy showed: the frame's own luminance is the target.
            ratio = originalLuma / max(proxyLuma, 1e-6);
        }
        else
        {
            // Above it, the difference is headroom the proxy could not represent -- brightness the
            // frame really has and the model never saw. It is handed back on top of the model's own
            // answer rather than scaled away, which is what kept highlights from being muted.
            ratio = (modelLuma + max(0.0, originalLuma - proxyLuma)) / modelLuma;
        }

        upgraded = lerp(original, HueOkLab(model * ratio, model), gTransferStrength);
    }

    // Detail strength decides how much of the model's picture is reached at all; colour strength
    // decides whether its colour comes with it. At 0 the frame keeps the game's own hue exactly and
    // only its light carries the model's verdict; at 1 the model's colour arrives as well.
    float upgradedLuma = dot(upgraded, kLuma);
    float lumaRatio = originalLuma > 1e-6 ? clamp(upgradedLuma / originalLuma, 0.0, gMaxRatio) : 1.0;

    /*
     * Where the model was shown a pixel it cannot represent, its colour there is not an opinion
     * worth taking.
     *
     * The encode normalises luminance but scales all three channels uniformly, so it bounds the luma
     * and not the channels. A bright saturated pixel therefore keeps a channel above 1.0 in the
     * proxy -- outside the display-referred range the model was trained on. It has no way to express
     * "green, brighter than white", so it returns near-white for that pixel, and the highlight branch
     * above then does its job correctly and carries that whiteness up to the frame's own luminance.
     * A neon light arrives white at full brightness.
     *
     * There is a design tension underneath this. The proxy is deliberately left bright enough to
     * clip, because the highlight branch is built on exactly that: originalLuma - proxyLuma is the
     * headroom the proxy could not represent, and dividing it away first leaves that branch nothing
     * to give back. So the clipping has to stay for luminance to come out right -- and the same
     * clipping is what destroys the chroma. This resolves the tension by keeping the clip and
     * declining only the colour damage it causes.
     *
     * Two conditions, and both are required:
     *
     *   clipped  how far the proxy left the model's range. Zero for anything inside it, which is
     *            almost the whole frame. This is the part that matters: where the model was working
     *            on a picture it could actually read, its colour is respected in full, including
     *            every deliberate shift of tone and light interaction it decided on. Judging by
     *            desaturation alone would have suppressed those too, and that is a real part of what
     *            the model does -- not something to throw away to fix a highlight.
     *
     *   kept     of the chroma it was given, how much came back. Only consulted where the pixel was
     *            out of range to begin with.
     *
     * A ratio rather than a difference, because the proxy and the model sit at different
     * brightnesses by construction and only the chroma fraction is comparable between them.
     *
     * None of this can fire in the passthrough path: an already tone-mapped frame is copied rather
     * than encoded, so the proxy is the original and nothing ever leaves the model's range. The
     * failure is specific to HDR because the encode is the only thing that creates it.
     */
    float colourStrength = gColourStrength;

    if (gColourGuard > 0.0 && gPassthrough == 0)
    {
        const float proxyPeak = max(proxy.r, max(proxy.g, proxy.b));

        // Ramped rather than switched: a hard test at 1.0 would draw a visible edge across a
        // gradient that crosses it.
        const float clipped = saturate((proxyPeak - 1.0) / 0.25);

        const float proxySat = Saturation(proxy);
        const float modelSat = Saturation(model);
        const float kept = proxySat > 1e-4 ? saturate(modelSat / proxySat) : 1.0;

        colourStrength *= lerp(1.0, kept, clipped * saturate(gColourGuard));
    }

    float3 result = lerp(original * lumaRatio, upgraded, colourStrength);

    // Back out of the normalised space the composition worked in.
    result *= normScale;

    gTarget[id.xy] = float4(max(result, float3(0.0, 0.0, 0.0)), originalSample.a);
}
